---
title: "Aktuelle Anstellung"
description: Informationen zu meiner derzeitigen Anstellung und die damit verbundenen Tätigkeiten.
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Wissenschaftliche Mitarbeiterin
----

**Abteilung für Persönlichkeits- und Entwicklungspsychologie, Universität Basel**

**(April 2021 - aktuell)**

### Projektmanagement und Datenerhebung, -aufbereitung und -analyse

Der Schwerpunkt meiner derzeitigen Tätigkeit liegt im **Projektmanagement** und in der **Datenanalyse** im Rahmen der Studie zur Überarbeitung des Fragebogens zur Erhebung der Emotionsregulation bei Kindern und Jugendlichen (FEEL-KJ).\
\
Dies beinhaltet oder beinhaltete folgende Projektaufgaben:
- Aktuell: Analyse der Daten der FEEL-KJ-Studie (in R Studio), Erledigung administrativer Aufgaben
die für den endgültigen Abschluss der Studie und die Aktualisierung des FEEL-KJ-Testmanuals erforderlich sind.
- Abschluss der Datenerhebung und -aufbereitung der FEEL-KJ-Studie. Dazu gehörte die persönliche Kontaktaufnahme mit relevanten Institutionen, die altersgerechte Präsentation der Studieninformationen vor Kindern und Jugendlichen zur Rekrutierung für die FEEL-KJ-Studie und die Beantwortung von Anfragen zur Studie von Institutionen und Teilnehmer:innen.
- Leitung und Koordination eines Teams von Praktikant:innen und Masterstudierenden, welche die Rekrutierung, Datenerfassung und -aufbereitung der FEEL-KJ-Studie unterstützten.
- Organisation und Abschluss der Datenerhebung für die FEEL-KJ-Pilotstudie zur Neunormierung und -Validierung des FEEL-KJs, sowie Datenaufbereitung und -analyse der Daten aus der Pilotstudie.
   
- Aufbau und Organisation sowohl der FEEL-KJ-Pilotstudie als auch der eigentlichen Studie zur Neunormierung und -Validierung des FEEL-KJs von Projektbeginn an, einschließlich der Literaturrecherche, der Auswahl der in die Studie einzubeziehenden Testbatterien, der Planung des Studienablaufes und der Ausarbeitung des Ethikantrages für die regionale Ethikkommission.
- Verwaltung der für die Durchführung der Studie erforderlichen administrativen Aufgaben, einschließlich der Beschaffung und Einrichtung der physischen und digitalen Datenverwaltungs- und Online-Umfrageinfrastruktur; letzteres in Zusammenarbeit mit dem IT-Team der Fakultät. Darüber hinaus Verantwortung für die Übersicht über die Studienausgaben, für die Beschaffung der Vergütung für die Studienteilnahme und für die Suche, Befragung und Einstellung von Praktikant:innen für die FEEL-KJ-Studie.

### Betreuung von Masterstudierenden

Einen kleineren, aber wichtigen, Fokus meiner derzeitigen Tätigkeit beinhaltete die **Betreuung von Masterstudierenden** im Rahmen des Masterprojekts _Testentwicklung_. Dies umfasste folgende Aufgaben:

- Betreuung und Unterstützung von Masterstudierenden während ihrer Masterarbeit. Dazu gehörten regelmäßige Treffen zur Besprechung des Fortschritts der Masterarbeit, schriftliches und mündliches Feedback zum Fortschritt der Masterarbeit, sowie die Bewertung und Erstellung des Gutachtens der Endfassung der Masterarbeit.
- Co-Supervision des an das Masterprojekt angrenzenden Kurses, zusammen mit zwei anderen Kolleg:innen. Dies beinhaltete die Besprechung des Kursplans und organisatorischer Angelegenheiten mit den Co-Supervisor:innen, die Planung, Vorbereitung und Durchführung von einzelnen Lektionen für die Masterstudierenden, die Bewertung von Hausaufgaben für die besagten Lektionen und die Rückmeldung zu den Präsentationen der Masterstudierenden.

Doktorandin
---

**Abteilung für Persönlichkeits- und Entwicklungspsychologie, Universität Basel**

**(April 2021 - aktuell)**\
\
Parallel zu meiner oben genannten Projektarbeit absolviere ich mein Doktorat an der Universität Basel. Das übergreifende Thema ist die Emotionsregulation negativer Emotionen bei Kindern und Jugendlichen. Das heißt, wie Kinder und Jugendliche mit ihrer Wut, Trauer und Angst umgehen.\
\
Um schließlich meinen Doktortitel zu erlangen, erledige oder erledigte ich die folgenden Tätigkeiten:

- Aktuell: Arbeit an meinem zweiten und dritten Manuskript.
- Präsentation von Forschungsergebnissen auf (internationalen) Konferenzen.
- Verfassung und Veröffentlichung wissenschaftlicher Artikel.
- Aufbereitung und Analyse verschiedener Datensätzen.
- Untersuchung relevanter Forschungsthemen für das übergreifende Thema meiner Dissertation und Formulierung relevanter Forschungsfragen, sowie Hypothesen.
- Regelmäßige Teilnahme an Workshops/Kursen zur Aneignung oder Verbesserung relevanter Softwareskills (z. B. spezifische Datenanalysemethoden) oder übertragbarer Fähigkeiten (z. B. Verbesserung allgemeiner Projektmanagementfähigkeiten).

