---
title: "Frühere Stellen und ehrenamtliche Tätigkeiten"
description: null
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Frühere Stellen

# Wissenschaftliche Assistentin

### Fachgruppe für Entwicklungs- und Familienpsychologie, ZHAW Zürcher Hochschule für Angewandte Wissenschaften

**(Januar 2020 - März 2021)**

- Datensammlung, -aufbereitung, -analyse und -visualisierung (in SPSS). Anschliessende Erstellung eines Forschungsberichts in Zusammenarbeit mit drei weiteren Projektmitgliedern über die oben genannten Daten, die während des ersten COVID-Lockdowns im Jahr 2020 erhoben wurden. Der [öffentlich zugängliche Bericht](https://moodle.zhaw.ch/pluginfile.php/244189/mod_label/intro/Ratgeber_digitales_Lernen_ZHAW.pdf) enthielt sowohl die Ergebnisse der Datenanalyse als auch Anregungen für die Studierenden der ZHAW, wie sie ihr Fernstudium über die Pandemie hinaus erfolgreich gestalten können.
- Datenaufbereitung und -analyse qualitativer Daten mittels Inhaltsanalyse (in MaxQDA). Anschliessende Erstellung eines Forschungsberichts auf der Grundlage der genannten Analyse über die Erfahrungen, die Pflegepersonal aus verschiedenen Pflegeeinrichtungen mit älteren Migrant:innen machen, und darüber, welche Hilfe sich das Pflegepersonal für eine bessere Pflege der älteren Migrant:innen wünschen würde.
- Übernahme verschiedener organisatorischer Tätigkeiten in der Fachgruppe, u.a. Unterstützung bei zwei internationalen Workshops, bei mehreren Online-Abschlusstests und bei der Bewertung von studentischen Seminararbeiten.

# Forschungspraktikum
      
### Professur für Klinische Psychologie mit Schwerpunkt Psychotherapieforschung, Universität Zürich

**(Juni 2018 - März 2019)**

- Datensammlung, -aufbereitung, -analyse und -visualisierung eines längsschnittlichen, klinischen Datensatzes (in SPSS und R Studio) mit depressiven Erwachsenen.
- Vorbereitung, Visualisierung und Präsentation eines Datenanalyse-Workshops zur inhaltlichen Auswertung von Audioaufnahmen aus dem Forschungsprojekt [TIDe - Telefon- Intervention bei Depression](https://psychologie.uzh.ch/de/bereiche/ hea/klipfor/forschung/abgeschlossene-Forschungsprojekte/TIDe.html).
- Übernahme diverser organisatorischer Aufgaben in der Abteilung, einschließlich Unterstützung bei einer wissenschaftlichen Konferenz.

# Psychologisches Praktikum

### Medizinisches Zentrum Geissberg, Kloten
**(Januar 2018 - März 2018)**

- Co-Supervision von Gruppentherapiesitzungen zweimal pro Woche
- Co-Supervision von wöchentlichem Training zur Stärkung des Selbstvetrauens der Patient:innen 
- Mehrfache Leitung der wöchentlichen Gruppenentspannungsübungen (z. B. progressive Muskelrelaxation)
- Durchführung von Tests mit Patienten, Analyse der Ergebnisse und Erstellung von Testberichten.
- Umsetzung des BASEL-Programms zur Behandlung von Fettleibigkeit in wöchentlichen Einzelsitzungen mit mehreren Patienten.
- Durchführung einer Expositionstherapie bei einem Patienten mit einer spezifischen Angststörung.
- Wahrnehmung verschiedener organisatorischer Aufgaben in der Abteilung, einschliesslich Protokollführung, Erstellung von Leitlinien und psychosoziale Unterstützung bei der administrativen Arbeit mit Patienten.

# Forschungspraktikum

### Professur für Entwicklungspsychologie: Erwachsenenalter, Universität Zürich

**(November 2016 - Februar 2017)**

- Bewertung, Vorbereitung, Analyse und Visualisierung eines großen Datensatzes mit Informationen über die Motivation, das Wohlbefinden, die Persönlichkeit und die Nutzung von Pokémon Go (in SPSS).
- Korrekturlesen von englischen und deutschen Manuskripten zur Vorbereitung auf die Veröffentlichung.
- Erledigung verschiedener organisatorischer Aufgaben in der Abteilung.

## Ehrenamtliche Tätigkeiten

# Illustratorin und Editorin

### aware - Zeitschrift für Psychologie, Universität Zürich

**(April 2017 - August 2019)**

- Erstellung von digitalen Originalillustrationen zu Artikeln meiner Wahl für jede Ausgabe der [Studentenzeitschrift für Psychologie](https://aware- psymagazin.ch/) (in Adobe Photoshop).
- Korrekturlesen und Redigieren von Artikeln als Redakteur für jede Ausgabe der Studentenzeitschrift für Psychologie.

Die erstellten Illustrationen und korrekturgelesenen, fertiggestellten Artikel sind hier verlinkt für die [Herbst 2017](https:// d1pdejp0rn9het.cloudfront.net/assets/aware_HS_17_9f49a8b480.pdf), [Frühjahr 2018](https://d1pdejp0rn9het.cloudfront.net/assets/ aware_FS_18_a4d56e0274.pdf), [Herbst 2018](https:// d1pdejp0rn9het.cloudfront.net/assets/aware_HS_18_4a2fb4bc4e.pdf), [Frühjahr 2019](https://d1pdejp0rn9het.cloudfront.net/assets/ aware_FS_19_db182f69d5.pdf) und [Herbst 2019](https:// d1pdejp0rn9het.cloudfront.net/assets/aware_HS_19_3f85db41c4.pdf) Semesterausgabe.

# Studierendenvertretung

### Berufungsskommission zweier Psychologieprofessuren für Entwicklungspsychologie im Kindes- und Jugendalters, Universität Zürich

**(August 2017 – August 2019)**

- Vertretung der Interessen der Psychologiestudierenden bei der Auswahl geeigneter Kandidat:innen für die Professur. 

# Vorstandsmitglied

### Fachverein Psychologie, Universität Zürich

**(November 2015 - April 2018)**

### Allgemein:
- Nahm regelmäßig an Organisationstreffen teil, beteiligte sich an Diskussionen über Themen, die die Studentenschaft betrafen und welche Maßnahmen die Studentenorganisation ergreifen würde.
- Mithilfe bei verschiedenen Aufgaben bei Veranstaltungen von Studentenorganisationen (z. B. Verkauf von Eintrittskarten für Veranstaltungen, Bedienung an der Kasse, Verteilung von Mahlzeiten am Essensstand, Verkauf von Eintrittskarten im Vorfeld der Veranstaltung usw.).

### Als Co-Leiterin des Ressorts Information (Oktober 2017 - April 2018):

- Verwaltung der E-Mail-Konten der Studentenorganisation und professionelle Kommunikation mit Personen, die sich mit allgemeinen Anfragen an die Organisation wenden
- Pflege und Aktualisierung der [Website der Studentenorganisation](https://www.faps.ch/).

### Als Co-Leiterin des Ressortmarketings (November 2015 - Oktober 2017):

- Organisation von Veranstaltungen, bei denen eingeladene Psychologen aus verschiedenen Bereichen der Psychologie Vorträge hielten und Fragen an Psychologiestudenten stellten
- Verbreitung des Bewusstseins über die Studentenorganisation