---
title: "Publikationen & Präsentationen"
description: Eine Übersicht meiner aktuellen Publikationen und Präsentationen, aufgelistet im APA 7 Format.   

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```
Publikationen
---
Grob, A., Smolenski, C. & Gasparovicova, L. (**in press**). *FEEL-KJ-2: Emotion Regulation Strategies Questionnaire*. Hogrefe Publishing Corporation. 

Gasparovicova, L., Meachon, E. J., & Grob, A. (2025). *European Questionnaires Assessing Emotion Regulation in Children and Adolescents: A Narrative Review* **[Manuskript in Druck]**. European Psychologist. 

Gasparovicova, L., Steppan, M., & Grob, A. (2025). *Executive Functioning as a Moderator between Emotion Regulation and Problem Behaviour in Typically-Developing Children and Adolescents* **[Manuskript in Vorbereitung]**. Abteilung für Persönlichkeits- und Entwicklungspsychologie, Universität Basel.

Gasparovicova, L. & Grob, A. (2025). *Revision of the Fragebogen zur Emotionsregulation bei Kindern und Jugendlichen (FEEL-KJ): Psychometric Qualities of the Fragebogen zur Emotionsregulation bei Kindern und Jugendlichen - 2 (FEEL-KJ - 2)* **[Manuskript in Vorbereitung]**. Abteilung für Persönlichkeits- und Entwicklungspsychologie, Universität Basel.

Schwarz, B., Härri, C., Gasparovicova, L. & von Arx, C. (2020). *Ratgeber zum digitalen Lernen
Erfolgreich Studieren im Online-Unterricht.* Zürcher Hochschule für Angewandte Wissenschaften. https://moodle.zhaw.ch/pluginfile.php/244189/mod_label/intro/Ratgeber_digitales_Lernen_ZHAW.pdf




Präsentationen & Poster
---

Präsentationen und Poster ---
Gasparovicova, L., Steppan, M., & Grob, A. (2024, September).
*Executive Functioning as a Moderator between Emotion Regulation and Problem Behaviour in Typically-Developing Children and Adolescents* Poster an der 4th Boost and Exchange Academic Conference (BEACON), Basel, Schweiz.

Gasparovicova, L., Meachon, E. J., & Grob, A. (2024, Juli). *Questionnaires Assessing Emotion Regulation in Children and Adolescents Validated in Europe* Präsentation auf der 45. Konferenz der International School Psychology Association (ISPA), Riga, Lettland.

Gasparovicova, L. & Grob, A. (2023, September). *Preliminary Analyses of the Standardisation Sample to Re-Standardize and Re-Validate the Fragebogen zur Erhebung der Emotionsregulation für Kinder und Jugendliche (FEEL-KJ)*. Poster an der 17. Arbeitstagung der Fachgruppe Differentielle
Psychologie, Persönlichkeitspsychologie und Psychologische Diagnostik
(DPPD) der Deutschen Gesellschaft für Psychologie, Salzburg, Österreich.

Gasparovicova, L. & Grob, A. (2022, September). *Conceptual Adjustment and Re-Validation of the Questionnaire for Assessment of Emotion Regulation in Children and Adolescents (German: Fragebogen zur Erhebung von Emotionsregulation bei Kindern und Jugendlichen, FEEL-KJ): A pilot study*. Poster an der 17. Konferenz der Schweizerischen Psychologischen Gesellschaft (SPS SGP SSP), Zürich, Schweiz.
