---
title: "Softwarekenntnisse und Soft Skills"
description: Ein kompakter Überblick über die Kenntnisse und übertragbaren Fähigkeiten im Umgang mit bestimmten Anwendungen, die ich in früheren oder aktuellen Anstellungen/Freiwilligentätigkeiten nachgewiesen habe. 
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Softwarekenntnisse
---

# RStudio
- Datenaufbereitung/Bereinigung
- Datenvisualisierung
- Datenanalyse, zum Beispiel:
  - Bewertung der psychometrischen Eigenschaften der verwendeten Messinstrumente, wie z. B. Reliabilitätsanalysen (z. B. Cronbachs Alpha, Omega Hierarchical usw.) und Analysen der zugrunde liegenden Strukturen (z. B. Hauptkomponentenanalyse [PCA], konfirmatorische Faktorenanalyse [CFA], Exploratory Structural Equation Modelling-within-CFA [ESEM- within- CFA])
  - Analyse fehlender Daten und mehrfache Imputation (z.B. Full- Information Maximum Likelihood
Schätzung [FIML], Multiple Imputation Chain Equation [MICE]) - Berechnung der deskriptiven Statistik
-   Berechnung von Inferenzstatistiken
-   Analyse der Gruppenunterschiede (t-Test, ANOVA)
-   Moderatoranalyse mit Strukturgleichungsmodellierung (SEM)
-  Analyse von genesteten Daten (Mehrebenenanalyse von multiplen Regressionen)

# IBM SPSS Statistics
- Datenaufbereitung/Bereinigung
- Datenvisualisierung
- Datenanalyse, zum Beispiel:
  - Bewertung der psychometrischen Eigenschaften der verwendeten Messinstrumente, wie z. B. Reliabilitätsanalysen (d. h. Intra-Klassen- Koeffizienten, Cronbachs Alpha)
  - Berechnung der Faktorenanalyse (d.h. PCA, EFA)
  - Berechnung der deskriptiven Statistik
  - Berechnung von Inferenzstatistiken
  - Analyse der Mittelwertunterschiede zwischen den Gruppen (t-Test, ANOVA) - Mehrfache hierachische Mediations- und Moderationsanalysen (mit dem PROCESS-Makro)

# G*Power
- Berechnung von A-priori-Power-Analysen zum Stichprobenbedarf für geplante Analysen

# LimeSurvey
- Konfiguration und Verwaltung von Online-Befragungen nach den aktuellen Schweizer
Datenschutzgesetze und ethische Richtlinien der Schweizer Ethikkommissionen (Swissethics)

# Adobe Photoshop
- Illustration von Originalbildern für Berichte, Präsentationen, Poster und Artikel
- Nachbearbeitung von Fotos 

# Microsoft Office-Anwendungen
- **Microsoft Word**:\
Schreiben verschiedener Vorlagen, Berichte und Manuskripte
- **Microsoft Excel**:\
Verfolgung des Studienfortschritts, vorläufige Datenbereinigung, sowie einfache Datenanalysen und -visualisierung
- **Microsoft PowerPoint**:\
Vorbereitung von Grafiken, Präsentationsfolien und wissenschaftlichen Postern
- **Microsoft Outlook**:\
Verfolgen, Verfassen und Organisieren von E-
Mails

# Microsoft Teams, Zoom und Slack
- Kommunikation, Organisation von Meetings und Dateifreigabe auf Microsoft Teams, Zoom und Slack

Soft Skills
---

# Datenerhebung und -analyse

- Erfahrung in der Datenerhebung (Festlegung und Verwaltung der physischen und digitale Infrastruktur, Kontaktaufnahme mit Institutionen, Rekrutierung von Teilnehmern) und Auswertung (Bewertung der gesammelten Daten anhand von Bewertungsschemata) von Daten, die menschliches Verhalten beschreiben
- Erfahrung in der Bereinigung, Aufbereitung und Analyse einer Reihe unterschiedlicher Datensätze (z. B. Stichprobengrößen zwischen 22 und 2000 Teilnehmern, typischerweise Entwicklungs- und klinische Stichproben, Daten von Minderjährigen und Erwachsenen, Analyse qualitativer Audio- und Interviewdaten sowie quantitativer Umfrage- und psychometrischer Testdaten) und Erfahrung mit verschiedener Software für statistische Analysen (IBM SPSS, R Studio) zur Analyse und Visualisierung von Daten, die menschliches Verhalten beschreiben

# Datenmanagement

- Erfahrung im Aufbau und in der Pflege einer übersichtlichen und leicht zu navigierenden Ordner- und Dateistruktur für ein gesamtes Projekt
- Erfahrung in der Kommunikation mit den zuständigen IT-Teams und in der Umsetzung ihrer Datenschutzmaßnahmen

# Projektorganisation und -management

- Erfahrung in der Vorbereitung eines Projekts (d. h. gründliche Ermittlung der erforderlichen Ressourcen und Kenntnisse, Planung und Organisation der erforderlichen Aufstellung des Projektplans, des Projektzeitplans usw.), der Einleitung und Verwaltung eines Projekts und seiner Mitglieder (d. h. Verfolgung des Projektfortschritts, Einstellung, Verwaltung und Unterstützung von Projektmitgliedern, flexible Anpassung an und Bewältigung von Herausforderungen während der Projektdurchführung) sowie der ordnungsgemäßen Beendigung eines Projekts (d. h. Analyse von Projektdaten, Erstellung von Projektabschlussberichten, Archivierung von Projektmaterial und -daten)
- Erstellung und Einreichung des Ethikberichts der geplanten Studie bei der zuständigen Ethikkommission, um sicherzustellen, dass die Projekte den schweizerischen Datenschutzgesetzen und ethischen Richtlinien entsprechen
- Suche, Vorstellungsgespräche und Einstellung von Praktikanten für die
Projektarbeit
- Koordinierung eines kleinen Teams von Mitarbeitern mit unterschiedlichen Arbeitsanteilen (z. B. 10 % - 50 %) und unterschiedlichen Zeitplänen, darunter:
  - Aufrechterhaltung einer guten und häufigen Kommunikation und des Austauschs relevanter Informationen zwischen den Projektmitgliedern
  - Ausbildung von Praktikanten und Masterstudenten für die Projektarbeit - Betreuung der Projektarbeit von Praktikanten und Masterstudenten
  - praktische und moralische Unterstützung für Praktikanten und Masterstudenten, wann immer dies erforderlich ist
  - Organisation regelmäßiger Treffen der Projektmitglieder, um alle
Projektmitglieder auf dem Laufenden zu halten und proaktiv mit aktuellen oder
erwarteten Herausforderungen während des laufenden Projekts umzugehen
- Arbeit innerhalb eines Projektteams als Projektmitglied, darunter:
  - Beitrag zu einem guten Arbeitsklima innerhalb des Projektteams mit guter und freundlicher Kommunikation
  - Erledigung von Aufgaben nach den Vorgaben meines Vorgesetzten sowie aktives Erfragen von Aufgabenspezifika oder Überarbeitung von Aufgabenergebnissen entsprechend dem Feedback des Vorgesetzten oder eines Projektmitglieds, wann immer dies erforderlich ist
  - Zusammenarbeit und Brainstorming mit anderen Projektmitgliedern zur Bewältigung größerer Aufgaben, die das gesamte Projektteam erfordern, und effektive Kommunikation für einen erfolgreichen Abschluss der Aufgaben
  - in Konfliktsituationen professionell und konstruktiv mit den Projektmitgliedern zu kommunizieren
  
# Bericht schreiben
- Erfahrung im Verfassen und Überarbeiten von (wissenschaftlichen) Berichten in englischer und deutscher Sprache
- Erfahrung in der Veröffentlichung englischsprachiger wissenschaftlicher Artikel und deutscher Berichte

# Korrekturlesen/redaktionelle Arbeit
- Erfahrung im Korrekturlesen und Redigieren von Texten (z. B. Artikel, Berichte, Dissertationen, Manuskripte) in englischer und deutscher Sprache im Hinblick auf grammatikalische Richtigkeit, Sprachstil und Form Einhaltung bestimmter Zitierformate (z. B. MLA 8. Auflage, APA 6. und 7. Auflage)
- Erfahrung in der Erteilung von konstruktivem Feedback zu Überarbeitungsvorschlägen, die sich aus der vorgenannten redaktionellen Arbeit ergeben

# Öffentliches Sprechen

- Erfahrung im öffentlichen Reden und Präsentieren in verschiedenen Kontexten (Konferenzpräsentation, Unterrichtsstunde, Studienpräsentation, Einladung zur Zusammenarbeit) vor verschiedenen Zuhörergruppen (Forscher, Studenten, Schüler, Fachleute aus dem Bereich der psychischen Gesundheit) unterschiedlicher Größe (5 bis 200 Personen) mit unterschiedlicher sprachlicher Komplexität (formale, wissenschaftliche Sprache vs. einfache Umgangssprache) und Vortragsdauer (3 bis 45 Minuten)

# Sprachkenntnisse

- **Standarddeutsch**:\
Sprach- und Schreibkenntnisse auf muttersprachlichem
das gesamte Schulleben in Deutschschweizer Schulen)
- **Schweizerdeutsch**:\
Verstehen und Sprechen auf muttersprachlichem Niveau (aufgewachsen in der Deutschschweiz)
- **Englisch**:\
Hohes Niveau in Wort und Schrift\
(Nebenfach Bachelor of Arts in Englischer Sprache und Literaturwissenschaft, Heimataufenthalt im Ausland in England)
- **Slowakisch**:\
Verstehen und Sprechen auf muttersprachlichem Niveau (slowakischer Muttersprachler)
- **Französisch**:\
Hohes Sprachniveau beim Verstehen, mittleres Sprachniveau beim Sprechen und Schreiben.
Niveau\ (besucht obligatorischer Französischunterricht in der Schule der 5. Klasse/Alter 10) - **Latein**:\
Mittleres Sprachniveau beim Verstehen und Schreiben\
(Unterricht in der Schule von der 7. Klasse/Alter 12 bis 12. Klasse/Alter 18)
- **Tschechisch**:\
Hohes Kompetenzniveau in Bezug auf das Verstehen